// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wedeli.Models.Domain.Data;

#nullable disable

namespace wedeli.Migrations.Company
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260112114126_InitialCompanySchema")]
    partial class InitialCompanySchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("wedeli.Models.Domain.CodTransaction", b =>
                {
                    b.Property<int>("CodTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cod_transaction_id");

                    b.Property<decimal?>("AdjustmentAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("adjustment_amount")
                        .HasDefaultValueSql("'0.00'")
                        .HasComment("Điều chỉnh (nếu có)");

                    b.Property<string>("AdjustmentReason")
                        .HasColumnType("text")
                        .HasColumnName("adjustment_reason");

                    b.Property<decimal>("CodAmount")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("cod_amount")
                        .HasComment("Số tiền thu hộ");

                    b.Property<DateTime?>("CollectedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("collected_at");

                    b.Property<int?>("CollectedByDriver")
                        .HasColumnType("int")
                        .HasColumnName("collected_by_driver")
                        .HasComment("Driver ID");

                    b.Property<string>("CollectionProofPhoto")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("collection_proof_photo")
                        .HasComment("Ảnh xác nhận thu tiền");

                    b.Property<string>("CollectionStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('pending','collected','failed')")
                        .HasColumnName("collection_status")
                        .HasDefaultValueSql("'pending'");

                    b.Property<decimal?>("CompanyFee")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("company_fee")
                        .HasDefaultValueSql("'0.00'")
                        .HasComment("Phí nhà xe trừ (nếu có)");

                    b.Property<int?>("CompanyReceivedBy")
                        .HasColumnType("int")
                        .HasColumnName("company_received_by")
                        .HasComment("Nhân viên nhà xe xác nhận nhận tiền");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<string>("OverallStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('pending_collection','collected','submitted_to_company','completed','failed')")
                        .HasColumnName("overall_status")
                        .HasDefaultValueSql("'pending_collection'");

                    b.Property<decimal?>("SubmittedAmount")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("submitted_amount")
                        .HasComment("Số tiền thực nộp (có thể khác nếu có phí)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("submitted_at");

                    b.Property<bool?>("SubmittedToCompany")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("submitted_to_company")
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("TransferMethod")
                        .HasColumnType("enum('cash','bank_transfer','e_wallet')")
                        .HasColumnName("transfer_method");

                    b.Property<string>("TransferProof")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("transfer_proof")
                        .HasComment("Ảnh/file chứng từ chuyển tiền");

                    b.Property<string>("TransferReference")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("transfer_reference");

                    b.Property<DateTime?>("TransferredAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("transferred_at");

                    b.Property<bool?>("TransferredToSender")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("transferred_to_sender")
                        .HasDefaultValueSql("'0'");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("CodTransactionId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CollectedByDriver" }, "collected_by_driver");

                    b.HasIndex(new[] { "CompanyReceivedBy" }, "company_received_by");

                    b.HasIndex(new[] { "OrderId" }, "order_id");

                    b.ToTable("cod_transactions");
                });

            modelBuilder.Entity("wedeli.Models.Domain.CompanyCustomer", b =>
                {
                    b.Property<int>("CompanyCustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("company_customer_id");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("CustomPrice")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("custom_price");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<decimal?>("DiscountPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("discount_percent");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsVip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_vip")
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<int>("TotalOrders")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("total_orders")
                        .HasDefaultValueSql("'0'");

                    b.Property<decimal>("TotalRevenue")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("total_revenue")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("CompanyCustomerId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CompanyId", "Phone" }, "idx_company_customer_phone");

                    b.HasIndex(new[] { "CompanyId", "CustomerId" }, "idx_company_customer_unique")
                        .IsUnique();

                    b.ToTable("company_customers");
                });

            modelBuilder.Entity("wedeli.Models.Domain.CompanyPartnership", b =>
                {
                    b.Property<int>("PartnershipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("partnership_id");

                    b.Property<decimal?>("CommissionRate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("commission_rate")
                        .HasDefaultValueSql("'0.00'")
                        .HasComment("% hoa hồng khi chuyển hàng");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id")
                        .HasComment("Nhà xe chính");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by")
                        .HasComment("Admin tạo quan hệ");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("PartnerCompanyId")
                        .HasColumnType("int")
                        .HasColumnName("partner_company_id")
                        .HasComment("Nhà xe đối tác quen");

                    b.Property<string>("PartnershipLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('preferred','regular','backup')")
                        .HasColumnName("partnership_level")
                        .HasDefaultValueSql("'regular'");

                    b.Property<int?>("PriorityOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("priority_order")
                        .HasDefaultValueSql("'0'")
                        .HasComment("Thứ tự ưu tiên (số càng nhỏ càng ưu tiên)");

                    b.Property<int?>("TotalTransferredOrders")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("total_transferred_orders")
                        .HasDefaultValueSql("'0'");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("PartnershipId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CreatedBy" }, "created_by");

                    b.HasIndex(new[] { "PartnerCompanyId" }, "partner_company_id");

                    b.HasIndex(new[] { "CompanyId", "PartnerCompanyId" }, "unique_partnership")
                        .IsUnique();

                    b.ToTable("company_partnerships");
                });

            modelBuilder.Entity("wedeli.Models.Domain.CompanyRole", b =>
                {
                    b.Property<int>("CompanyRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("company_role_id");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("role_name");

                    b.HasKey("CompanyRoleId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CompanyId", "RoleName" }, "idx_company_role_unique")
                        .IsUnique();

                    b.ToTable("company_roles");
                });

            modelBuilder.Entity("wedeli.Models.Domain.CompanyUser", b =>
                {
                    b.Property<int>("CompanyUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("company_user_id");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<int>("CompanyRoleId")
                        .HasColumnType("int")
                        .HasColumnName("company_role_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("username");

                    b.HasKey("CompanyUserId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CompanyId" }, "idx_company_users_company");

                    b.HasIndex(new[] { "CompanyRoleId" }, "idx_company_users_role");

                    b.HasIndex(new[] { "Username" }, "idx_company_users_username")
                        .IsUnique();

                    b.ToTable("company_users");
                });

            modelBuilder.Entity("wedeli.Models.Domain.Complaint", b =>
                {
                    b.Property<int>("ComplaintId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("complaint_id");

                    b.Property<string>("ComplaintStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('pending','investigating','resolved','rejected')")
                        .HasColumnName("complaint_status")
                        .HasDefaultValueSql("'pending'");

                    b.Property<string>("ComplaintType")
                        .IsRequired()
                        .HasColumnType("enum('lost','damaged','late','wrong_address','other')")
                        .HasColumnName("complaint_type");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EvidencePhotos")
                        .HasColumnType("text")
                        .HasColumnName("evidence_photos")
                        .HasComment("JSON array of photo URLs");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<string>("ResolutionNotes")
                        .HasColumnType("text")
                        .HasColumnName("resolution_notes");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("resolved_at");

                    b.Property<int?>("ResolvedBy")
                        .HasColumnType("int")
                        .HasColumnName("resolved_by");

                    b.HasKey("ComplaintId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CustomerId" }, "customer_id");

                    b.HasIndex(new[] { "OrderId" }, "order_id")
                        .HasDatabaseName("order_id1");

                    b.HasIndex(new[] { "ResolvedBy" }, "resolved_by");

                    b.ToTable("complaints");
                });

            modelBuilder.Entity("wedeli.Models.Domain.DailyActivityLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("log_id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("action")
                        .HasComment("created, updated, deleted, transferred, etc");

                    b.Property<int?>("ChangedBy")
                        .HasColumnType("int")
                        .HasColumnName("changed_by")
                        .HasComment("User thực hiện thay đổi");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int")
                        .HasColumnName("entity_id")
                        .HasComment("ID của entity");

                    b.Property<string>("EntityType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("entity_type")
                        .HasComment("orders, vehicles, drivers, etc");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<DateOnly>("LogDate")
                        .HasColumnType("date")
                        .HasColumnName("log_date");

                    b.Property<string>("LogType")
                        .IsRequired()
                        .HasColumnType("enum('order','payment','transfer','vehicle','complaint','system')")
                        .HasColumnName("log_type");

                    b.Property<string>("NewValue")
                        .HasColumnType("text")
                        .HasColumnName("new_value")
                        .HasComment("Giá trị mới (JSON)");

                    b.Property<string>("OldValue")
                        .HasColumnType("text")
                        .HasColumnName("old_value")
                        .HasComment("Giá trị cũ (JSON)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.HasKey("LogId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ChangedBy" }, "changed_by");

                    b.HasIndex(new[] { "EntityType", "EntityId" }, "idx_entity");

                    b.HasIndex(new[] { "LogDate" }, "idx_log_date");

                    b.HasIndex(new[] { "LogType" }, "idx_log_type");

                    b.ToTable("daily_activity_logs");
                });

            modelBuilder.Entity("wedeli.Models.Domain.DailySummary", b =>
                {
                    b.Property<int>("SummaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("summary_id");

                    b.Property<decimal?>("AvgDeliveriesPerDriver")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("avg_deliveries_per_driver")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<int?>("ComplaintsResolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("complaints_resolved")
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("GeneratedBy")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("generated_by")
                        .HasDefaultValueSql("'system'");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("last_updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("PendingCodAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("pending_cod_amount")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<DateOnly>("SummaryDate")
                        .HasColumnType("date")
                        .HasColumnName("summary_date");

                    b.Property<decimal?>("TotalCodCollected")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("total_cod_collected")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<decimal?>("TotalCodSubmitted")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("total_cod_submitted")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<int?>("TotalComplaints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("total_complaints")
                        .HasDefaultValueSql("'0'");

                    b.Property<int?>("TotalDriversActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("total_drivers_active")
                        .HasDefaultValueSql("'0'");

                    b.Property<int?>("TotalOrdersCancelled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("total_orders_cancelled")
                        .HasDefaultValueSql("'0'");

                    b.Property<int?>("TotalOrdersCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("total_orders_created")
                        .HasDefaultValueSql("'0'");

                    b.Property<int?>("TotalOrdersDelivered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("total_orders_delivered")
                        .HasDefaultValueSql("'0'");

                    b.Property<int?>("TotalOrdersTransferred")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("total_orders_transferred")
                        .HasDefaultValueSql("'0'");

                    b.Property<decimal?>("TotalRevenue")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("total_revenue")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<int?>("TotalTripsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("total_trips_completed")
                        .HasDefaultValueSql("'0'");

                    b.Property<int?>("TotalVehiclesActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("total_vehicles_active")
                        .HasDefaultValueSql("'0'");

                    b.Property<int?>("TotalVehiclesOverloaded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("total_vehicles_overloaded")
                        .HasDefaultValueSql("'0'");

                    b.HasKey("SummaryId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SummaryDate" }, "idx_summary_date")
                        .IsUnique();

                    b.ToTable("daily_summary");
                });

            modelBuilder.Entity("wedeli.Models.Domain.Driver", b =>
                {
                    b.Property<int>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("driver_id");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<int>("CompanyUserId")
                        .HasColumnType("int")
                        .HasColumnName("company_user_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DriverLicense")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("driver_license");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active")
                        .HasDefaultValueSql("'1'");

                    b.Property<DateOnly?>("LicenseExpiry")
                        .HasColumnType("date")
                        .HasColumnName("license_expiry");

                    b.Property<decimal?>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("rating")
                        .HasDefaultValueSql("'5.00'");

                    b.Property<decimal?>("SuccessRate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("success_rate")
                        .HasDefaultValueSql("'100.00'");

                    b.Property<int?>("TotalTrips")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("total_trips")
                        .HasDefaultValueSql("'0'");

                    b.HasKey("DriverId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CompanyId" }, "company_id");

                    b.HasIndex(new[] { "CompanyUserId" }, "company_user_id");

                    b.ToTable("drivers");
                });

            modelBuilder.Entity("wedeli.Models.Domain.DriverCodSummary", b =>
                {
                    b.Property<int>("SummaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("summary_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DriverId")
                        .HasColumnType("int")
                        .HasColumnName("driver_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal?>("PendingAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("pending_amount")
                        .HasDefaultValueSql("'0.00'")
                        .HasComment("Số tiền chưa nộp");

                    b.Property<DateTime?>("ReconciledAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("reconciled_at");

                    b.Property<int?>("ReconciledBy")
                        .HasColumnType("int")
                        .HasColumnName("reconciled_by")
                        .HasComment("Admin xác nhận đối soát");

                    b.Property<string>("ReconciliationStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('pending','reconciled','discrepancy')")
                        .HasColumnName("reconciliation_status")
                        .HasDefaultValueSql("'pending'");

                    b.Property<DateOnly>("SummaryDate")
                        .HasColumnType("date")
                        .HasColumnName("summary_date");

                    b.Property<decimal?>("TotalCodCollected")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("total_cod_collected")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<decimal?>("TotalCodSubmitted")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("total_cod_submitted")
                        .HasDefaultValueSql("'0.00'");

                    b.HasKey("SummaryId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ReconciledBy" }, "reconciled_by");

                    b.HasIndex(new[] { "DriverId", "SummaryDate" }, "unique_driver_date")
                        .IsUnique();

                    b.ToTable("driver_cod_summary");
                });

            modelBuilder.Entity("wedeli.Models.Domain.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("notification_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_read")
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasColumnType("enum('order_status','payment','promotion','system')")
                        .HasColumnName("notification_type");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<string>("SentVia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('sms','email','push','all')")
                        .HasColumnName("sent_via")
                        .HasDefaultValueSql("'push'");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("NotificationId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "OrderId" }, "order_id")
                        .HasDatabaseName("order_id2");

                    b.HasIndex(new[] { "UserId" }, "user_id");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("wedeli.Models.Domain.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<decimal?>("CodAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("cod_amount")
                        .HasDefaultValueSql("'0.00'")
                        .HasComment("Tiền thu hộ");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<decimal?>("DeclaredValue")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("declared_value");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("delivered_at");

                    b.Property<int?>("DriverId")
                        .HasColumnType("int")
                        .HasColumnName("driver_id");

                    b.Property<string>("OrderStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('pending_pickup','picked_up','in_transit','out_for_delivery','delivered','returned','cancelled')")
                        .HasColumnName("order_status")
                        .HasDefaultValueSql("'pending_pickup'");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("paid_at");

                    b.Property<string>("ParcelType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('fragile','electronics','food','cold','document','other')")
                        .HasColumnName("parcel_type")
                        .HasDefaultValueSql("'other'");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("enum('cash','bank_transfer','e_wallet','periodic')")
                        .HasColumnName("payment_method");

                    b.Property<string>("PaymentStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('unpaid','paid','pending')")
                        .HasColumnName("payment_status")
                        .HasDefaultValueSql("'unpaid'");

                    b.Property<DateTime?>("PickupConfirmedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("pickup_confirmed_at");

                    b.Property<DateTime?>("PickupScheduledAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("pickup_scheduled_at");

                    b.Property<string>("ReceiverAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("receiver_address");

                    b.Property<string>("ReceiverDistrict")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("receiver_district");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("receiver_name");

                    b.Property<string>("ReceiverPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("receiver_phone");

                    b.Property<string>("ReceiverProvince")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("receiver_province");

                    b.Property<int?>("RouteId")
                        .HasColumnType("int")
                        .HasColumnName("route_id");

                    b.Property<string>("SenderAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sender_address");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("sender_name");

                    b.Property<string>("SenderPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("sender_phone");

                    b.Property<decimal>("ShippingFee")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("shipping_fee");

                    b.Property<string>("SpecialInstructions")
                        .HasColumnType("text")
                        .HasColumnName("special_instructions");

                    b.Property<string>("TrackingCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tracking_code");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int")
                        .HasColumnName("vehicle_id");

                    b.Property<decimal?>("WeightKg")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("OrderId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "DriverId" }, "driver_id");

                    b.HasIndex(new[] { "CreatedAt" }, "idx_orders_created_at");

                    b.HasIndex(new[] { "CustomerId" }, "idx_orders_customer");

                    b.HasIndex(new[] { "OrderStatus" }, "idx_orders_status");

                    b.HasIndex(new[] { "TrackingCode" }, "idx_orders_tracking")
                        .IsUnique();

                    b.HasIndex(new[] { "RouteId" }, "route_id");

                    b.HasIndex(new[] { "VehicleId" }, "vehicle_id");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("wedeli.Models.Domain.OrderPhoto", b =>
                {
                    b.Property<int>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("photo_id");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("file_name");

                    b.Property<int?>("FileSizeKb")
                        .HasColumnType("int")
                        .HasColumnName("file_size_kb");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<string>("PhotoType")
                        .IsRequired()
                        .HasColumnType("enum('before_delivery','after_delivery','parcel_condition','signature','damage_proof')")
                        .HasColumnName("photo_type");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("photo_url")
                        .HasComment("URL từ cloud storage (AWS S3, Cloudinary, etc)");

                    b.Property<DateTime?>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("UploadedBy")
                        .HasColumnType("int")
                        .HasColumnName("uploaded_by");

                    b.HasKey("PhotoId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "OrderId" }, "order_id")
                        .HasDatabaseName("order_id3");

                    b.HasIndex(new[] { "UploadedBy" }, "uploaded_by");

                    b.ToTable("order_photos");
                });

            modelBuilder.Entity("wedeli.Models.Domain.OrderStatusHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("history_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("location");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("new_status");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("OldStatus")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("old_status");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.HasKey("HistoryId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "OrderId" }, "order_id")
                        .HasDatabaseName("order_id4");

                    b.HasIndex(new[] { "UpdatedBy" }, "updated_by");

                    b.ToTable("order_status_history");
                });

            modelBuilder.Entity("wedeli.Models.Domain.OrderTransfer", b =>
                {
                    b.Property<int>("TransferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("transfer_id");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("accepted_at");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("text")
                        .HasColumnName("admin_notes");

                    b.Property<decimal?>("CommissionPaid")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("commission_paid")
                        .HasDefaultValueSql("'0.00'")
                        .HasComment("Hoa hồng trả cho đối tác");

                    b.Property<int>("FromCompanyId")
                        .HasColumnType("int")
                        .HasColumnName("from_company_id");

                    b.Property<int?>("NewVehicleId")
                        .HasColumnType("int")
                        .HasColumnName("new_vehicle_id");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<int?>("OriginalVehicleId")
                        .HasColumnType("int")
                        .HasColumnName("original_vehicle_id")
                        .HasComment("Xe ban đầu bị đầy");

                    b.Property<int>("ToCompanyId")
                        .HasColumnType("int")
                        .HasColumnName("to_company_id");

                    b.Property<decimal?>("TransferFee")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("transfer_fee")
                        .HasDefaultValueSql("'0.00'")
                        .HasComment("Phí chuyển đổi (nếu có)");

                    b.Property<string>("TransferReason")
                        .IsRequired()
                        .HasColumnType("enum('vehicle_full','route_unavailable','emergency','partnership','other')")
                        .HasColumnName("transfer_reason");

                    b.Property<string>("TransferStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('pending','accepted','rejected','completed')")
                        .HasColumnName("transfer_status")
                        .HasDefaultValueSql("'pending'");

                    b.Property<DateTime?>("TransferredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("transferred_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("TransferredBy")
                        .HasColumnType("int")
                        .HasColumnName("transferred_by")
                        .HasComment("Admin thực hiện chuyển");

                    b.HasKey("TransferId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "FromCompanyId" }, "from_company_id");

                    b.HasIndex(new[] { "NewVehicleId" }, "new_vehicle_id");

                    b.HasIndex(new[] { "OrderId" }, "order_id")
                        .HasDatabaseName("order_id5");

                    b.HasIndex(new[] { "OriginalVehicleId" }, "original_vehicle_id");

                    b.HasIndex(new[] { "ToCompanyId" }, "to_company_id");

                    b.HasIndex(new[] { "TransferredBy" }, "transferred_by");

                    b.ToTable("order_transfers");
                });

            modelBuilder.Entity("wedeli.Models.Domain.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("payment_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("paid_at");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("enum('cash','bank_transfer','e_wallet')")
                        .HasColumnName("payment_method");

                    b.Property<string>("PaymentStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('pending','completed','failed')")
                        .HasColumnName("payment_status")
                        .HasDefaultValueSql("'pending'");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("enum('shipping_fee','cod_collection','refund')")
                        .HasColumnName("payment_type");

                    b.Property<string>("TransactionRef")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("transaction_ref");

                    b.HasKey("PaymentId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CustomerId" }, "customer_id")
                        .HasDatabaseName("customer_id1");

                    b.HasIndex(new[] { "PaymentStatus" }, "idx_payments_status");

                    b.HasIndex(new[] { "OrderId" }, "order_id")
                        .HasDatabaseName("order_id6");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("wedeli.Models.Domain.PeriodicInvoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("invoice_id");

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasColumnType("enum('weekly','biweekly','monthly','custom')")
                        .HasColumnName("billing_cycle")
                        .HasComment("Chu kỳ do nhà xe quy định");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id")
                        .HasComment("Nhà xe phát hành hóa đơn");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("InvoicePeriod")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("invoice_period")
                        .HasComment("YYYY-MM hoặc YYYY-Wxx hoặc custom range");

                    b.Property<string>("InvoiceStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('pending','paid','overdue','cancelled')")
                        .HasColumnName("invoice_status")
                        .HasDefaultValueSql("'pending'");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal?>("PaidAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("paid_amount")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("paid_at");

                    b.Property<string>("PaymentTerms")
                        .HasColumnType("text")
                        .HasColumnName("payment_terms")
                        .HasComment("Điều khoản thanh toán riêng của nhà xe");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("total_amount");

                    b.HasKey("InvoiceId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CompanyId" }, "company_id")
                        .HasDatabaseName("company_id1");

                    b.HasIndex(new[] { "CustomerId" }, "customer_id")
                        .HasDatabaseName("customer_id2");

                    b.ToTable("periodic_invoices");
                });

            modelBuilder.Entity("wedeli.Models.Domain.Rating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rating_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<int?>("DriverId")
                        .HasColumnType("int")
                        .HasColumnName("driver_id");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<int?>("RatingScore")
                        .HasColumnType("int")
                        .HasColumnName("rating_score");

                    b.Property<string>("ReviewText")
                        .HasColumnType("text")
                        .HasColumnName("review_text");

                    b.HasKey("RatingId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CustomerId" }, "customer_id")
                        .HasDatabaseName("customer_id3");

                    b.HasIndex(new[] { "DriverId" }, "driver_id")
                        .HasDatabaseName("driver_id1");

                    b.HasIndex(new[] { "OrderId" }, "order_id")
                        .HasDatabaseName("order_id7");

                    b.ToTable("ratings");
                });

            modelBuilder.Entity("wedeli.Models.Domain.Route", b =>
                {
                    b.Property<int>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("route_id");

                    b.Property<decimal?>("BasePrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("base_price");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DestinationDistrict")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("destination_district");

                    b.Property<string>("DestinationProvince")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("destination_province");

                    b.Property<decimal?>("DistanceKm")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("distance_km");

                    b.Property<decimal?>("EstimatedDurationHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("estimated_duration_hours");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("OriginDistrict")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("origin_district");

                    b.Property<string>("OriginProvince")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("origin_province");

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("route_name");

                    b.HasKey("RouteId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CompanyId" }, "company_id")
                        .HasDatabaseName("company_id2");

                    b.ToTable("routes");
                });

            modelBuilder.Entity("wedeli.Models.Domain.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("trip_id");

                    b.Property<DateTime?>("ArrivalTime")
                        .HasColumnType("timestamp")
                        .HasColumnName("arrival_time");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DepartureTime")
                        .HasColumnType("timestamp")
                        .HasColumnName("departure_time");

                    b.Property<int>("DriverId")
                        .HasColumnType("int")
                        .HasColumnName("driver_id");

                    b.Property<bool?>("IsReturnTrip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_return_trip")
                        .HasDefaultValueSql("'0'")
                        .HasComment("Chuyến về (E2)");

                    b.Property<int>("RouteId")
                        .HasColumnType("int")
                        .HasColumnName("route_id");

                    b.Property<int?>("TotalOrders")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("total_orders")
                        .HasDefaultValueSql("'0'");

                    b.Property<decimal?>("TotalWeightKg")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("total_weight_kg")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<DateOnly>("TripDate")
                        .HasColumnType("date")
                        .HasColumnName("trip_date");

                    b.Property<string>("TripStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('scheduled','in_progress','completed','cancelled')")
                        .HasColumnName("trip_status")
                        .HasDefaultValueSql("'scheduled'");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int")
                        .HasColumnName("vehicle_id");

                    b.HasKey("TripId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "DriverId" }, "driver_id")
                        .HasDatabaseName("driver_id2");

                    b.HasIndex(new[] { "TripDate", "TripStatus" }, "idx_trips_date");

                    b.HasIndex(new[] { "RouteId" }, "route_id")
                        .HasDatabaseName("route_id1");

                    b.HasIndex(new[] { "VehicleId" }, "vehicle_id")
                        .HasDatabaseName("vehicle_id1");

                    b.ToTable("trips");
                });

            modelBuilder.Entity("wedeli.Models.Domain.TripOrder", b =>
                {
                    b.Property<int>("TripOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("trip_order_id");

                    b.Property<bool?>("DeliveryConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("delivery_confirmed")
                        .HasDefaultValueSql("'0'");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<bool?>("PickupConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("pickup_confirmed")
                        .HasDefaultValueSql("'0'");

                    b.Property<int?>("SequenceNumber")
                        .HasColumnType("int")
                        .HasColumnName("sequence_number")
                        .HasComment("Thứ tự giao hàng");

                    b.Property<int>("TripId")
                        .HasColumnType("int")
                        .HasColumnName("trip_id");

                    b.HasKey("TripOrderId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "OrderId" }, "order_id")
                        .HasDatabaseName("order_id8");

                    b.HasIndex(new[] { "TripId" }, "trip_id");

                    b.ToTable("trip_orders");
                });

            modelBuilder.Entity("wedeli.Models.Domain.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("vehicle_id");

                    b.Property<bool?>("AllowOverload")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("allow_overload")
                        .HasDefaultValueSql("'0'")
                        .HasComment("Admin cho phép thêm hàng nhẹ");

                    b.Property<decimal?>("CapacityPercentage")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("capacity_percentage")
                        .HasDefaultValueSql("'0.00'")
                        .HasComment("% tải trọng");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CurrentStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('available','in_transit','maintenance','inactive','overloaded')")
                        .HasColumnName("current_status")
                        .HasDefaultValueSql("'available'");

                    b.Property<decimal?>("CurrentWeightKg")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("current_weight_kg")
                        .HasDefaultValueSql("'0.00'")
                        .HasComment("Trọng tải hiện tại");

                    b.Property<bool?>("GpsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("gps_enabled")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("license_plate");

                    b.Property<decimal?>("MaxVolumeM3")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("max_volume_m3");

                    b.Property<decimal?>("MaxWeightKg")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("max_weight_kg");

                    b.Property<decimal?>("OverloadThreshold")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("overload_threshold")
                        .HasDefaultValueSql("'95.00'")
                        .HasComment("Ngưỡng cảnh báo đầy (%)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("enum('truck','van','motorbike')")
                        .HasColumnName("vehicle_type");

                    b.HasKey("VehicleId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CompanyId" }, "company_id")
                        .HasDatabaseName("company_id3");

                    b.HasIndex(new[] { "LicensePlate" }, "license_plate")
                        .IsUnique();

                    b.ToTable("vehicles");
                });

            modelBuilder.Entity("wedeli.Models.Domain.VehicleLocation", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("location_id");

                    b.Property<decimal?>("Accuracy")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("accuracy");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("Heading")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("heading");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("decimal(10,8)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("decimal(11,8)")
                        .HasColumnName("longitude");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("recorded_at");

                    b.Property<decimal?>("Speed")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("speed");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int")
                        .HasColumnName("vehicle_id");

                    b.HasKey("LocationId");

                    b.HasIndex(new[] { "RecordedAt" }, "idx_vehicle_locations_recorded_at");

                    b.HasIndex(new[] { "VehicleId" }, "idx_vehicle_locations_vehicle_id");

                    b.ToTable("vehicle_locations");
                });

            modelBuilder.Entity("wedeli.Models.Domain.WarehouseStaff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("staff_id");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<int>("CompanyUserId")
                        .HasColumnType("int")
                        .HasColumnName("company_user_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("WarehouseLocation")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("warehouse_location");

                    b.HasKey("StaffId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CompanyId" }, "company_id")
                        .HasDatabaseName("company_id4");

                    b.HasIndex(new[] { "CompanyUserId" }, "company_user_id")
                        .HasDatabaseName("company_user_id1");

                    b.ToTable("warehouse_staff");
                });

            modelBuilder.Entity("wedeli.Models.Domain.CodTransaction", b =>
                {
                    b.HasOne("wedeli.Models.Domain.Driver", "CollectedByDriverNavigation")
                        .WithMany("CodTransactions")
                        .HasForeignKey("CollectedByDriver")
                        .HasConstraintName("cod_transactions_ibfk_2");

                    b.HasOne("wedeli.Models.Domain.Order", "Order")
                        .WithMany("CodTransactions")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("cod_transactions_ibfk_1");

                    b.Navigation("CollectedByDriverNavigation");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("wedeli.Models.Domain.CompanyUser", b =>
                {
                    b.HasOne("wedeli.Models.Domain.CompanyRole", "CompanyRole")
                        .WithMany("CompanyUsers")
                        .HasForeignKey("CompanyRoleId")
                        .IsRequired()
                        .HasConstraintName("company_users_role_fk");

                    b.Navigation("CompanyRole");
                });

            modelBuilder.Entity("wedeli.Models.Domain.Complaint", b =>
                {
                    b.HasOne("wedeli.Models.Domain.Order", "Order")
                        .WithMany("Complaints")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("complaints_ibfk_1");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("wedeli.Models.Domain.Driver", b =>
                {
                    b.HasOne("wedeli.Models.Domain.CompanyUser", "CompanyUser")
                        .WithMany("Drivers")
                        .HasForeignKey("CompanyUserId")
                        .IsRequired()
                        .HasConstraintName("drivers_company_user_fk");

                    b.Navigation("CompanyUser");
                });

            modelBuilder.Entity("wedeli.Models.Domain.DriverCodSummary", b =>
                {
                    b.HasOne("wedeli.Models.Domain.Driver", "Driver")
                        .WithMany("DriverCodSummaries")
                        .HasForeignKey("DriverId")
                        .IsRequired()
                        .HasConstraintName("driver_cod_summary_ibfk_1");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("wedeli.Models.Domain.Notification", b =>
                {
                    b.HasOne("wedeli.Models.Domain.Order", "Order")
                        .WithMany("Notifications")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("notifications_ibfk_2");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("wedeli.Models.Domain.Order", b =>
                {
                    b.HasOne("wedeli.Models.Domain.Driver", "Driver")
                        .WithMany("Orders")
                        .HasForeignKey("DriverId")
                        .HasConstraintName("orders_ibfk_4");

                    b.HasOne("wedeli.Models.Domain.Route", "Route")
                        .WithMany("Orders")
                        .HasForeignKey("RouteId")
                        .HasConstraintName("orders_ibfk_2");

                    b.HasOne("wedeli.Models.Domain.Vehicle", "Vehicle")
                        .WithMany("Orders")
                        .HasForeignKey("VehicleId")
                        .HasConstraintName("orders_ibfk_3");

                    b.Navigation("Driver");

                    b.Navigation("Route");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("wedeli.Models.Domain.OrderPhoto", b =>
                {
                    b.HasOne("wedeli.Models.Domain.Order", "Order")
                        .WithMany("OrderPhotos")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("order_photos_ibfk_1");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("wedeli.Models.Domain.OrderStatusHistory", b =>
                {
                    b.HasOne("wedeli.Models.Domain.Order", "Order")
                        .WithMany("OrderStatusHistories")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("order_status_history_ibfk_1");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("wedeli.Models.Domain.OrderTransfer", b =>
                {
                    b.HasOne("wedeli.Models.Domain.Vehicle", "NewVehicle")
                        .WithMany("OrderTransferNewVehicles")
                        .HasForeignKey("NewVehicleId")
                        .HasConstraintName("order_transfers_ibfk_5");

                    b.HasOne("wedeli.Models.Domain.Order", "Order")
                        .WithMany("OrderTransfers")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("order_transfers_ibfk_1");

                    b.HasOne("wedeli.Models.Domain.Vehicle", "OriginalVehicle")
                        .WithMany("OrderTransferOriginalVehicles")
                        .HasForeignKey("OriginalVehicleId")
                        .HasConstraintName("order_transfers_ibfk_4");

                    b.Navigation("NewVehicle");

                    b.Navigation("Order");

                    b.Navigation("OriginalVehicle");
                });

            modelBuilder.Entity("wedeli.Models.Domain.Payment", b =>
                {
                    b.HasOne("wedeli.Models.Domain.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("payments_ibfk_1");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("wedeli.Models.Domain.Rating", b =>
                {
                    b.HasOne("wedeli.Models.Domain.Driver", "Driver")
                        .WithMany("Ratings")
                        .HasForeignKey("DriverId")
                        .HasConstraintName("ratings_ibfk_3");

                    b.HasOne("wedeli.Models.Domain.Order", "Order")
                        .WithMany("Ratings")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("ratings_ibfk_1");

                    b.Navigation("Driver");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("wedeli.Models.Domain.Trip", b =>
                {
                    b.HasOne("wedeli.Models.Domain.Driver", "Driver")
                        .WithMany("Trips")
                        .HasForeignKey("DriverId")
                        .IsRequired()
                        .HasConstraintName("trips_ibfk_3");

                    b.HasOne("wedeli.Models.Domain.Route", "Route")
                        .WithMany("Trips")
                        .HasForeignKey("RouteId")
                        .IsRequired()
                        .HasConstraintName("trips_ibfk_1");

                    b.HasOne("wedeli.Models.Domain.Vehicle", "Vehicle")
                        .WithMany("Trips")
                        .HasForeignKey("VehicleId")
                        .IsRequired()
                        .HasConstraintName("trips_ibfk_2");

                    b.Navigation("Driver");

                    b.Navigation("Route");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("wedeli.Models.Domain.TripOrder", b =>
                {
                    b.HasOne("wedeli.Models.Domain.Order", "Order")
                        .WithMany("TripOrders")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("trip_orders_ibfk_2");

                    b.HasOne("wedeli.Models.Domain.Trip", "Trip")
                        .WithMany("TripOrders")
                        .HasForeignKey("TripId")
                        .IsRequired()
                        .HasConstraintName("trip_orders_ibfk_1");

                    b.Navigation("Order");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("wedeli.Models.Domain.VehicleLocation", b =>
                {
                    b.HasOne("wedeli.Models.Domain.Vehicle", "Vehicle")
                        .WithMany("VehicleLocations")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("wedeli.Models.Domain.WarehouseStaff", b =>
                {
                    b.HasOne("wedeli.Models.Domain.CompanyUser", "CompanyUser")
                        .WithMany("WarehouseStaffs")
                        .HasForeignKey("CompanyUserId")
                        .IsRequired()
                        .HasConstraintName("warehouse_staff_company_user_fk");

                    b.Navigation("CompanyUser");
                });

            modelBuilder.Entity("wedeli.Models.Domain.CompanyRole", b =>
                {
                    b.Navigation("CompanyUsers");
                });

            modelBuilder.Entity("wedeli.Models.Domain.CompanyUser", b =>
                {
                    b.Navigation("Drivers");

                    b.Navigation("WarehouseStaffs");
                });

            modelBuilder.Entity("wedeli.Models.Domain.Driver", b =>
                {
                    b.Navigation("CodTransactions");

                    b.Navigation("DriverCodSummaries");

                    b.Navigation("Orders");

                    b.Navigation("Ratings");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("wedeli.Models.Domain.Order", b =>
                {
                    b.Navigation("CodTransactions");

                    b.Navigation("Complaints");

                    b.Navigation("Notifications");

                    b.Navigation("OrderPhotos");

                    b.Navigation("OrderStatusHistories");

                    b.Navigation("OrderTransfers");

                    b.Navigation("Payments");

                    b.Navigation("Ratings");

                    b.Navigation("TripOrders");
                });

            modelBuilder.Entity("wedeli.Models.Domain.Route", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("wedeli.Models.Domain.Trip", b =>
                {
                    b.Navigation("TripOrders");
                });

            modelBuilder.Entity("wedeli.Models.Domain.Vehicle", b =>
                {
                    b.Navigation("OrderTransferNewVehicles");

                    b.Navigation("OrderTransferOriginalVehicles");

                    b.Navigation("Orders");

                    b.Navigation("Trips");

                    b.Navigation("VehicleLocations");
                });
#pragma warning restore 612, 618
        }
    }
}
